[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFFFF"
secondaryBackgroundColor = "#C2C5E1FF"
textColor = "#000000FF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
